version: '3.3'
services:
  php:
    image: php:7.4-apache
    volumes:
      - ./docker/php/conf/php.ini:/usr/local/etc/php/php.ini
      - ./www/html:/var/www/html
    ports:
      - 80:80
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db
