version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "18080:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log/:/var/log/nginx/
